"""Add categories

Revision ID: bd990dfa418d
Revises: 804d96ded152
Create Date: 2026-07-17 12:50:23.210998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd990dfa418d'
down_revision: Union[str, None] = '804d96ded152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tournament_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('matches', sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_constraint('matches_tournament_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'categories', ['category_id'], ['id'])
    op.drop_column('matches', 'tournament_id')
    op.add_column('rounds', sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_constraint('rounds_tournament_id_fkey', 'rounds', type_='foreignkey')
    op.create_foreign_key(None, 'rounds', 'categories', ['category_id'], ['id'])
    op.drop_column('rounds', 'tournament_id')
    op.add_column('teams', sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_constraint('teams_tournament_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'categories', ['category_id'], ['id'])
    op.drop_column('teams', 'tournament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_tournament_id_fkey', 'teams', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('teams', 'category_id')
    op.add_column('rounds', sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.create_foreign_key('rounds_tournament_id_fkey', 'rounds', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('rounds', 'category_id')
    op.add_column('matches', sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_tournament_id_fkey', 'matches', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('matches', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
